NUM_GPUS: 2
DATASET:
  NAME: pascal_voc
  CROP_SIZE: 321
  SCALE_FROM: 0.9
  SCALE_TO: 1.0
TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 25
  NUM_WORKERS: 8
  PRETRAIN: 5
NET:
  NUM_CLASSES: 21
  BACKBONE: "resnet38"
  MODEL: "ae"
  PRE_WEIGHTS_PATH: "./pretrained_pool/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth"
  LR: 0.001
  OPT: "SGD"
  LOSS: "SoftMargin"
  WEIGHT_DECAY: 0.0005
TEST:
  FLIP: True
  SCALES: [1, 0.5, 1.5, 2.0]
  USE_GT_LABELS: False
  FP_CUT_SCORE: 0.1
